// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActiveChats: typeof import('./components/ActiveChats.vue')['default'];
    Contacts: typeof import('./components/Contacts.vue')['default'];
    Footer: typeof import('./components/Footer.vue')['default'];
    Logos: typeof import('./components/Logos.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
